version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t package

  build:
    commands:
      - echo Creating Lambda deployment package...
      - cd package
      - zip -r ../function.zip .
      - cd ..
      - zip -g function.zip lambda_function.py

artifacts:
  files:
    - function.zip
